---
#YAML FILE START

__main__: "DEBUG"

##### DB SYNC #####
wattrex_cycler_db_sync: "INFO"
db_sync.src.wattrex_cycler_db_sync: "DEBUG"
##### DRV ######
scpi_sniffer: "DEBUG"

##### SYS #####
system_logger_tool: "ERROR"
system_shared_tool: "ERROR"
system_config_tool: "ERROR"

file_handlers: {}