version: '3.8'

services:
  cache_db:
    #image: linuxserver/mariadb
    image: tobi312/rpi-mariadb:10.11-alpine
    container_name: wattrex_cycler_cache_db
    restart: always
    ports:
      - "3366:3306"
    volumes:
      - wattrex_cycler_cache_db:/var/lib/mysql:rw
      - ./cache_db/createCacheCyclerTables.sql:/docker-entrypoint-initdb.d/createCacheCyclerTables.sql
    environment:
      TZ: Europe/Berlin
    env_file:
      - ../config/.cred.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${MARIADB_ROOT_USER}", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - wattrex-net

  cycler:
    build:
      context: ../
      dockerfile: ./devops/cycler/Dockerfile.cycler
      target: ${CYCLER_TARGET}
      args:
        USER: ${USER_ID}
        GROUP: ${GROUP_ID}
    image: robertoaldea/wattrex-cycler-node:latest
    restart: no
    # user: ${USER_ID}:${GROUP_ID}
    ipc: host
    volumes:
      - ../config/.cred.yaml:/cycler/config/.cred.yaml
      - ../config/cycler/log_config.yaml:/cycler/config/cycler/log_config.yaml
      - ../log:/cycler/log
      - ../config/config_params.yaml:/cycler/config/config_params.yaml
    networks:
      - wattrex-net
    depends_on:
      cache_db:
        condition: service_healthy

  db_sync:
    build:
      context: ../
      dockerfile: ./devops/db_sync/Dockerfile.db_sync
      target: ${CYCLER_TARGET}
      args:
        USER: ${USER_ID}
        GROUP: ${GROUP_ID}
    image: robertoaldea/wattrex-cycler-db-sync:latest
    container_name: wattrex_cycler_db_sync
    restart: always
    #user: ${USER_ID}:${GROUP_ID}
    ipc: host
    volumes:
      - ./db_sync/run_db_sync.py:/cycler/devops/db_sync/run_db_sync.py
      - ../config/.cred.yaml:/cycler/config/.cred.yaml
      - ../config/db_sync/log_config.yaml:/cycler/config/db_sync/log_config.yaml
      - ../log:/cycler/log
    networks:
      - wattrex-net
    depends_on:
      cache_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "${MASTER_MYSQL_HOST}", "-u${MASTER_MYSQL_USER}", "-p${MASTER_MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  wattrex_cycler_cache_db:
    name: wattrex_cycler_cache_db

networks:
  wattrex-net:
    driver: bridge
