---
#YAML FILE START
APP.APP_MODULE: "CRITICAL" #APP/APP_MODULE/APP_EXAMPLE.py

__main__: "INFO"

##### DEV ######
wattrex_cycler_cu_manager: "DEBUG"
cu_manager.src.wattrex_cycler_cu_manager: "DEBUG"

##### DRV ######
wattrex_driver_mqtt: "ERROR"
can_sniffer: "ERROR"
scpi_sniffer: "ERROR"

##### SYS #####
sys_abs.sys_conf: "ERROR"
system_logger_tool: "ERROR"
system_shared_tool: "ERROR"
system_config_tool: "ERROR"

file_handlers: {}