---

master_db:
  user: ???
  password: ???
  host: ???.???.???.???
  port: ???
  database: wattrex_master_db

cache_db:
    user: ???
    password: ???
    database: wattrex_cache_db
    root_password: ???
    host: cache_db
    port: 3306

mqtt:
  user: ???
  password: ???
  host: ???.???.???.???
  port: 1883
