--- #YAML FILE START

__main__: "DEBUG"

##### app #####
app.app_man: "DEBUG"
app.app_diag: "DEBUG"

##### mid #####
mid.mid_dabs: "DEBUG"
mid.mid_meas: "DEBUG"
mid.mid_data: "DEBUG"
mid.mid_str: "DEBUG"

##### drv ######
wattrex_driver_epc: 'WARNING'
wattrex_driver_ea: 'INFO'
wattrex_driver_rs: 'INFO'
wattrex_driver_pwr: 'INFO'
wattrex_driver_bk: 'INFO'
scpi_sniffer: 'INFO'
can_sniffer: 'INFO'

##### sys #####
system_shared_tool: "INFO"
system_config_tool: "INFO"
system_logger_tool: "INFO"

test_mid_dabs: 'DEBUG'
file_handlers: {
  # "log_can" : [ drv.drv_can, drv.drv_epc ],
}