# This workflow deploys battery cycler controller to development environment

name: Deploy cycler to STAGING

on:
  workflow_call:

jobs:
  # build-docker-image:
  #   name: Build docker image
  #   if: ${{ github.event.review.state == 'approved' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Build and export
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: ./devops/docker/Dockerfile.cycler
  #         tags: wattrex-cycler:latest
  #         outputs: type=docker,dest=/tmp/wattrex-cycler.tar
  #         push: false

  launch-real-bat:
    name: Launch cycler controller in real environment
    # if: ${{ github.event.review.state == 'approved' && contains(fromJson(vars.CYCLER_BRANCHES), github.event.pull_request.head.ref) }}
    # needs: build-docker-image
    uses: ./.github/workflows/02_05_staging_deploy_real_bat.yml
    secrets: inherit
