# This workflow deploys battery cycler controller to development environment

name: Deployment of battery cycler controller to development environment

on:
  push:
    branches:
      - "app_diag"
      - "app_man"
      - "mid_data"
      - "mid_meas"
      - "mid_dabs"
      - "mid_str"
      - "mid_pwr"

jobs:

  detect-folder:
    runs-on: ubuntu-latest
    outputs:
      folder: ${{ steps.step1.outputs.folder }}
    steps:
      - name: "Set env variables"
        id: step1
        run: |
          echo "::set-output name=folder::$(echo ${{ github.ref_name }} | cut -d'_' -f 1)"
    
  build-package:
    name: QA and Build battery controller on ${{ github.ref_name }} push
    needs: detect-folder
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: "${{ vars.CYCLER_PACKAGE_NAME }}"
      package-path: "code/cycler"
      source-path: "code/cycler/src/${{ vars.CYCLER_PACKAGE_NAME }}/${{ needs.detect-folder.outputs.folder }}/${{ github.ref_name }}"
      python-version: "3.10"

  publish-package:
    name: Publish ${{ vars.CYCLER_PACKAGE_NAME }} package to Test PyPi
    needs: build-package
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name:  "${{ vars.CYCLER_PACKAGE_NAME }}"
          path: "${{ vars.CYCLER_PACKAGE_NAME }}/dist/"

      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e #realse/v1.8.10
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: "${{ vars.CYCLER_PACKAGE_NAME }}/dist/"
